### ISSUE TITLE
code and dataset release

### ISSUE THREAD

**Issue by lzw-lzw** [ChenDelong1999/RemoteCLIP#1]
Hi, thanks for your excellent work, I wonder if you would release the code and the dataset you use?

**Comment by ChenDelong1999** [comment]
Sorry but we are not able to release the dataset for RemoteCLIP pretraining. 

Our implementation is based on [OpenCLIP](https://github.com/mlfoundations/open_clip) and [ITRA](https://itra.readthedocs.io/en/latest/) (which is derived from OpenCLIP). If you plan to re-implement RemoteCLIP, I feel OpenCLIP is a good codebase to get started.
