### ISSUE TITLE
Huggingface cannot be opened

### ISSUE THREAD

**Issue by Zhao-yan056** [ChenDelong1999/RemoteCLIP#16]
Hi，
I have tried many times recently but the huggingface website cannot be accessed. Is it possible to upload the pre-trained model to other websites? This will effectively help me use this pre-trained model.

**Comment by ChenDelong1999** [comment]
It seems that the huggingface repo is still on, have you tried VPN if you are visiting from mainland?

![image](https://github.com/ChenDelong1999/RemoteCLIP/assets/31244423/68d809e1-7530-40f2-b427-7662755d70c9)

**Comment by Zhao-yan056** [comment]
I have tried VPN many times but still failed to load.
![图片](https://github.com/ChenDelong1999/RemoteCLIP/assets/83754429/d08364a5-80bb-415b-bbeb-d04e44ada97e)

**Comment by ChenDelong1999** [comment]
Hi @Zhao-yan056 , have you successfully accessed the RemoteCLIP weights? If you still have trouble downloading it from Huggingface, we can provide a Baidu Netdisk alternative.
