### ISSUE TITLE
Box to caption 

### ISSUE THREAD

**Issue by lzwqjh** [ChenDelong1999/RemoteCLIP#17]
Hi, I am very interested in your work. We have some remote sensing related data that need to be captioned. Could you please provide us with your specific box to caption code? I would be grateful if you could get a reply.

**Comment by ChenDelong1999** [comment]
Unfortunately, we could not offer the codes, sorry. However, implementing B2C and M2B is quite straightforward. For re-implementation, you might refer to the Algorithm 1 in the arxiv v1 version: https://arxiv.org/pdf/2306.11029v1.pdf

![image](https://github.com/ChenDelong1999/RemoteCLIP/assets/31244423/e84a5737-dceb-4c5f-8f61-50d56fe28e0a)
