### ISSUE TITLE
论文在算法层面的创新疑惑

### ISSUE THREAD

**Issue by zhangyuereal** [ChenDelong1999/RemoteCLIP#19]
论文的出发点挺好的，工作也很扎实。
但是有一点疑惑，模型架构是不是就是原封不对的clip模型？

**Comment by ChenDelong1999** [comment]
张老师好！

我们RemoteCLIP的模型架构直接继承了CLIP，论文的贡献主要在于数据集的构建、基础模型的训练评测与开源。

感谢关注。

**Comment by zhangyuereal** [comment]
谢谢。懂了



---- 回复的原邮件 ----
| 发件人 | Delong Chen ***@***.***> |
| 日期 | 2024年01月09日 11:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ChenDelong1999/RemoteCLIP] 论文在算法层面的创新疑惑 (Issue #19) |

张老师好！

我们RemoteCLIP的模型架构直接继承了CLIP，论文的贡献主要在于数据集的构建、基础模型的训练评测与开源。

感谢关注。
