### ISSUE TITLE
How to split train/test in linear-prob, knn?

### ISSUE THREAD

**Issue by chagmgang** [ChenDelong1999/RemoteCLIP#2]

**Comment by ChenDelong1999** [comment]
Hi, sorry for missing this detail in our paper. 

In classification experiments of both linear-prob and k-NN, we use a spliting ratio of **train:test=8:2**.

**Comment by chagmgang** [comment]
Thank you for reply.
Is it splited randomly?

**Comment by ChenDelong1999** [comment]
Hi, sorry for missing previous comment.

Many of the classification dataset do not provide official train/val/test split, therefore we have to do this by our own. In our implementation, for each class, we use the first 80% samples (starting from something like `001.jpg`, `002.jpg` ...) for training, and  use the remaining for testing.

**Comment by chagmgang** [comment]
Thank you reply.
