### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by whut265107** [ChenDelong1999/RemoteCLIP#21]
Could you provide Remote CLIP available dataset ?

**Comment by ChenDelong1999** [comment]
The dataset will be open-sourced as soon as our paper is accepted : )

**Comment by zcablii** [comment]
This is impressive work! I do have a small query regarding the intellectual property rights involved. Given the combination of numerous datasets, I was curious to know if authorization was obtained from the original publishers of these datasets?

**Comment by ChenDelong1999** [comment]
Thank you!

We might release only the generated textual captions and corresponding dataset & image IDs.
