### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by BradNeuberg** [ChenDelong1999/RemoteCLIP#23]
There’s no license in the repo, what license are the trained RemoteCLIP weights under? For comparison, the RSICD CLIP model is under an Apache 2 license.

RSICD CLIP license: https://github.com/arampacha/CLIP-rsicd/blob/master/LICENSE

**Comment by ChenDelong1999** [comment]
License is created, thanks : )

**Comment by BradNeuberg** [comment]
Thanks :)
