### ISSUE TITLE
一图多caption的相似度矩阵计算干扰问题

### ISSUE THREAD

**Issue by YiguoHe** [ChenDelong1999/RemoteCLIP#25]
您好，您的工作非常具有创新性，给caption生成带来了一套简单实用的方法，非常感谢你们的工作。
我有一个问题想要请教一下，当CLIP计算相似度矩阵的时候，一个图像有多个caption的话，矩阵计算的时候会将其他四个视为负样本，那么就会对结果造成干扰。请问你们是如何处理模型训练和验证过程中的“一图多文相互干扰”的问题的呢？谢谢！

**Comment by rongtongxueya** [comment]
same question.can give me some  advice?

**Comment by ranck626** [comment]
有解决吗？？
