### ISSUE TITLE
[To Fix]:TGRS version Typo 

### ISSUE THREAD

**Issue by Bili-Sakura** [ChenDelong1999/RemoteCLIP#38]
A typo in Liu, F., Chen, D., Guan, Z., Zhou, X., Zhu, J., Ye, Q., ... & Zhou, J. (2024). Remoteclip: A vision language foundation model for remote sensing. IEEE Transactions on Geoscience and Remote Sensing. [TGRS version Link](https://ieeexplore.ieee.org/abstract/document/10504785)

Original:

```
...SimCLR [2], mean absolute error (MAE) [3], and ...
```

Corrected:

```
...SimCLR [2], Masked Autoencoder (MAE) [3], and ...
```

Snapshot:

![image](https://github.com/user-attachments/assets/af1344c5-7c11-4855-b552-dbf4aeeb4b4f)

**Comment by ChenDelong1999** [comment]
Oh thank you for pointing this out. I guess the full names are added by the TGRS editors. Our submitted final version is the same as the latest arxiv (v4) version, which do not have the full names. We will contact the journal. Thanks : )



---Original---
From: ***@***.***&gt;
Date: Sat, Aug 17, 2024 10:28 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [ChenDelong1999/RemoteCLIP] [To Fix]:TGRS version Typo  (Issue #38)




 
A typo in Liu, F., Chen, D., Guan, Z., Zhou, X., Zhu, J., Ye, Q., ... &amp; Zhou, J. (2024). Remoteclip: A vision language foundation model for remote sensing. IEEE Transactions on Geoscience and Remote Sensing. TGRS version Link
 
Original:
 ...SimCLR [2], mean absolute error (MAE) [3], and ...  
Corrected:
 ...SimCLR [2], Masked Autoencoder (MAE) [3], and ...  
Snapshot:
 
image.png (view on web)
