### ISSUE TITLE
Can you provide the retrieval evaluation code?

### ISSUE THREAD

**Issue by chagmgang** [ChenDelong1999/RemoteCLIP#4]

**Comment by ChenDelong1999** [comment]
Our implementation is based on OpenCLIP and ITRA (which is derived from OpenCLIP). You may refer to this file for details of our retrieval evaluation implementation:

https://github.com/ChenDelong1999/ITRA/blob/main/itra/evaluation/retrieval.py

We have also used the [GaLR codebase](https://github.com/xiaoyuan1996/GaLR) for verifying our implementation, you may see their codes as well.
