### ISSUE TITLE
Can you open the B2C, M2B code?

### ISSUE THREAD

**Issue by chagmgang** [ChenDelong1999/RemoteCLIP#5]

**Comment by ChenDelong1999** [comment]
Unfortunately we could not offer the codes, sorry. However, implememnting B2C and M2B is quite straight-forward, most of our work is for downloading and curating different datasets ...

For re-implementation, you might refer to the Algorithm 1 in the arxiv v1 version: https://arxiv.org/pdf/2306.11029v1.pdf

![image](https://github.com/ChenDelong1999/RemoteCLIP/assets/31244423/1a1b976b-c5f2-4937-bf2b-ec3af3f75862)
